// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountSys: typeof import('./src/components/AccountSys.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDivider: typeof import('vant/es')['Divider']
    Web3Api: typeof import('./src/components/Web3Api.vue')['default']
  }
}
